version: '3.3'
services:
  backend:
    image: a7medayman6/library-management-system
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mysql:8.0
    #restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'library-management-system-db'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    # volumes:
    #   - library-management-system-db:/var/lib/mysql
  seed:
    image: a7medayman6/library-management-system
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - db
      - backend
    command: npm run seed

  test:
    image: a7medayman6/library-management-system
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - db
      - backend
    command: npm run test

  
volumes:
  library-management-system-db:
